gemfile: Gemfile

PreCommit:
  BundleCheck:
    enabled: true

  ExecutePermissions:
    enabled: true
    exclude:
      - 'bin/propose'

  HardTabs:
    enabled: true

  RuboCop:
    enabled: true
    command: ['bundle', 'exec', 'rubocop']

  TrailingWhitespace:
    enabled: true
