AllCops:
  Include:
    - '**/*.gemspec'
    - '**/Gemfile'
    - '**/*.rake'
    - '**/Rakefile'
  TargetRubyVersion: 2.4 # Oldest version of Ruby this gem needs to support

# Allow developers to pass regexes as arguments without enclosing parens, e.g.
#
#   response.body.should match /some regex/
Lint/AmbiguousRegexpLiteral:
  Enabled: false

# We use this pattern a lot in our code base.
Lint/AssignmentInCondition:
  Enabled: false

# Avoid lines longer than 100 characters. The theory is that there are times
# where forcing a wrap to 80 characters can actually harm readability, but if
# you're hitting 100 there is probably a way to condense what you're trying to
# express.
Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  CountComments: false
  Max: 20

# Don't bother checking alignment of arguments to functions--there are too many
# edge cases which look funny if we follow this rule strictly.
Layout/AlignParameters:
  Enabled: false

# Don't require nested modules/classes to be on separate lines.
Style/ClassAndModuleChildren:
  Enabled: false

# Don't enforce using full lambda syntax for multi-line lambda blocks.
Style/Lambda:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

# Spreading method chains over multiple lines shouldn't require you to force
# indentation at 2 spaces.
Layout/MultilineOperationIndentation:
  Enabled: false

# Prefer curly braces except for %i/%w/%W, since those return arrays.
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%': '{}'
    '%i': '[]'
    '%q': '{}'
    '%Q': '{}'
    '%r': '{}'
    '%s': '()'
    '%w': '[]'
    '%W': '[]'
    '%x': '{}'

# Forcing the name of a predicate to `doctor?` makes it difficult to tell if it
# is a "has-a" or a "is-a" predicate, so disable it.
Naming/PredicateName:
  Enabled: false

# Disable enforcing `raise` keyword only inside `rescue` blocks. This check had
# widespread disapproval.
Style/SignalException:
  Enabled: false

# Forcing the naming of arguments to `reduce` to be `|a, e|` isn't very useful.
Style/SingleLineBlockParams:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false
