language: ruby

cache: bundler

rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7

before_script:
  - git config --global user.email "travis@travis.ci"
  - git config --global user.name "Travis CI"

script:
  - bundle exec rspec
  - bundle exec overcommit --sign
  - bundle exec overcommit --run
