language: ruby

sudo: false

cache: bundler

rvm:
  - 2.0
  - 2.1
  - 2.2

before_script:
  - git config --global user.email "travis@travis.ci"
  - git config --global user.name "Travis CI"

script:
  - bundle exec rspec
  - bundle exec overcommit --run
